[2024-05-18T20:19:52.140+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-18T20:19:52.153+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_loader.upload_file manual__2024-05-18T20:19:01.641651+00:00 [queued]>
[2024-05-18T20:19:52.159+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_loader.upload_file manual__2024-05-18T20:19:01.641651+00:00 [queued]>
[2024-05-18T20:19:52.160+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 3
[2024-05-18T20:19:52.171+0000] {taskinstance.py:2330} INFO - Executing <Task(LocalFilesystemToGCSOperator): upload_file> on 2024-05-18 20:19:01.641651+00:00
[2024-05-18T20:19:52.177+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2273) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-18T20:19:52.179+0000] {standard_task_runner.py:63} INFO - Started process 2275 to run task
[2024-05-18T20:19:52.179+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'data_loader', 'upload_file', 'manual__2024-05-18T20:19:01.641651+00:00', '--job-id', '361', '--raw', '--subdir', 'DAGS_FOLDER/data_loader.py', '--cfg-path', '/tmp/tmp86iy66na']
[2024-05-18T20:19:52.181+0000] {standard_task_runner.py:91} INFO - Job 361: Subtask upload_file
[2024-05-18T20:19:52.227+0000] {task_command.py:426} INFO - Running <TaskInstance: data_loader.upload_file manual__2024-05-18T20:19:01.641651+00:00 [running]> on host b5cbc22da81e
[2024-05-18T20:19:52.289+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_loader' AIRFLOW_CTX_TASK_ID='upload_file' AIRFLOW_CTX_EXECUTION_DATE='2024-05-18T20:19:01.641651+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-18T20:19:01.641651+00:00'
[2024-05-18T20:19:52.291+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-18T20:19:52.298+0000] {connection.py:274} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-05-18T20:19:52.300+0000] {base.py:84} INFO - Using connection ID 'googlecloud' for task execution.
[2024-05-18T20:19:52.301+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-18T20:19:52.302+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/transfers/local_to_gcs.py", line 98, in execute
    raise FileNotFoundError(self.src)
FileNotFoundError: .\data_example.txt
[2024-05-18T20:19:52.309+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=data_loader, task_id=upload_file, run_id=manual__2024-05-18T20:19:01.641651+00:00, execution_date=20240518T201901, start_date=20240518T201952, end_date=20240518T201952
[2024-05-18T20:19:52.319+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 361 for task upload_file (.\data_example.txt; 2275)
[2024-05-18T20:19:52.354+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-18T20:19:52.375+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-18T20:19:52.378+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
